//! Integration tests for phase 03 — the acceptance criteria of ROADMAP phase 03, one by one.
//!
//! Everything here runs against **real files, decoded by the bundled ffmpeg**, in a temporary
//! library folder that is deleted afterwards. Mocking the decoder would leave the whole phase
//! untested: the interesting failures are ffmpeg's — a silent video, a truncated container, a
//! format whose extension promises one thing and whose bytes say another.
//!
//! The test media is **generated by ffmpeg at run time** rather than versioned. It keeps the
//! repository free of binaries (ROADMAP §C forbids committing media), and it makes the fixtures
//! reproducible: every one of them is a line of `lavfi` in this file.

use std::path::{Path, PathBuf};

use sillage_lib::ingest::{
    formats, DuplicatePolicy, Ingested, Ingestor, Stabilization, Tool, Tools, MINIMUM_DURATION_MS,
};
use sillage_lib::library::Library;
use sillage_lib::model::peaks::DEFAULT_BUCKET_MS;
use sillage_lib::model::TranscriptStatus;

// ---------------------------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------------------------

/// The bundled binaries, or `None` with a loud note.
///
/// `scripts/fetch-resources.ps1` puts them there. A test that quietly passed without them would
/// let phase 03 be declared verified on a machine where nothing was ever decoded.
fn tools() -> Option<Tools> {
    let tools = Tools::in_directory(Path::new(env!("CARGO_MANIFEST_DIR")).join("resources"));
    if tools.are_present() {
        Some(tools)
    } else {
        eprintln!(
            "IGNORÉ : {} est absent — lancer scripts/fetch-resources.ps1.",
            tools.path(Tool::Ffmpeg).display()
        );
        None
    }
}

/// A world for one test: the binaries, a library folder and a scratch folder for source files.
struct World {
    _dir: tempfile::TempDir,
    tools: Tools,
    ingestor: Ingestor,
    library: Library,
    sources: PathBuf,
}

fn world() -> Option<World> {
    let tools = tools()?;
    let dir = tempfile::tempdir().expect("tempdir");
    let sources = dir.path().join("sources");
    std::fs::create_dir_all(&sources).expect("sources");

    Some(World {
        ingestor: Ingestor::new(tools.clone()).with_stabilization(Stabilization::immediate()),
        library: Library::open(dir.path().join("Sillage")).expect("library"),
        tools,
        sources,
        _dir: dir,
    })
}

impl World {
    /// Runs ffmpeg with the given arguments, producing `name` in the sources folder.
    fn produce(&self, name: &str, args: &[&str]) -> PathBuf {
        use std::ffi::OsStr;

        let path = self.sources.join(name);
        let mut full: Vec<&OsStr> = vec![
            OsStr::new("-y"),
            OsStr::new("-loglevel"),
            OsStr::new("error"),
        ];
        full.extend(args.iter().map(OsStr::new));
        full.push(path.as_os_str());

        let finished = self.tools.run(Tool::Ffmpeg, &full).expect("run ffmpeg");
        assert!(
            finished.succeeded,
            "could not produce {name}: {}",
            finished.stderr
        );
        path
    }

    /// `seconds` of tone in whatever container `name`'s extension names.
    fn tone(&self, name: &str, seconds: f32) -> PathBuf {
        self.produce(
            name,
            &[
                "-f",
                "lavfi",
                "-i",
                &format!("sine=frequency=440:sample_rate=44100:duration={seconds}"),
            ],
        )
    }

    fn ingest(&self, source: &Path) -> Result<Ingested, sillage_lib::ingest::IngestError> {
        self.ingestor
            .ingest(&self.library, source, DuplicatePolicy::Ask)
    }

    /// Ingests and unwraps to the added transcript, failing the test on a refusal.
    fn added(&self, source: &Path) -> sillage_lib::model::Transcript {
        match self.ingest(source) {
            Ok(Ingested::Added(transcript)) => *transcript,
            Ok(Ingested::Duplicate { .. }) => {
                panic!("unexpected duplicate for {}", source.display())
            }
            Err(error) => panic!("{} was refused: {error}", source.display()),
        }
    }

    /// The message of a refusal, failing the test if the file was accepted.
    fn refusal(&self, source: &Path) -> sillage_lib::ingest::IngestError {
        match self.ingest(source) {
            Err(error) => error,
            Ok(_) => panic!("{} should have been refused", source.display()),
        }
    }
}

// ---------------------------------------------------------------------------------------------
// « Un fichier de chaque format listé s'ingère »
// ---------------------------------------------------------------------------------------------

#[test]
fn one_file_of_every_accepted_format_is_ingested() {
    let Some(world) = world() else { return };

    // The video containers need a picture as well as sound, or they would be testing the silent
    // case instead. A 32×32 colour source is enough and keeps the files tiny.
    let audio = [
        "-f",
        "lavfi",
        "-i",
        "sine=frequency=440:sample_rate=44100:duration=2",
    ];
    let with_picture = [
        "-f",
        "lavfi",
        "-i",
        "color=c=blue:s=32x32:r=5:d=2",
        "-f",
        "lavfi",
        "-i",
        "sine=frequency=440:sample_rate=44100:duration=2",
        "-shortest",
    ];

    let mut ingested = Vec::new();

    for extension in formats::all_extensions() {
        let name = format!("essai.{extension}");
        let path = if formats::kind_of(extension) == Some(formats::MediaKind::Video) {
            world.produce(&name, &with_picture)
        } else {
            world.produce(&name, &audio)
        };

        let transcript = world.added(&path);
        assert!(
            transcript.media_path.ends_with(&format!(".{extension}")),
            "the copy must keep the original extension: {}",
            transcript.media_path
        );
        assert!(
            transcript.duration_ms >= 1_900 && transcript.duration_ms <= 2_100,
            "{extension}: duration {} ms is not the 2 s produced",
            transcript.duration_ms
        );
        assert_eq!(transcript.status, TranscriptStatus::Queued, "{extension}");
        ingested.push(extension);
    }

    assert_eq!(ingested.len(), formats::all_extensions().len());
    assert_eq!(
        world.library.db().count_transcripts().expect("count") as usize,
        ingested.len()
    );
}

#[test]
fn an_ingested_file_leaves_a_complete_entry_behind() {
    let Some(world) = world() else { return };
    let source = world.tone("Entretien Marchand.wav", 4.0);

    let transcript = world.added(&source);
    let paths = world.library.paths();

    // The copy, under the internal identifier, with the original extension (CONCEPTION §3.4).
    let media = paths.resolve(&transcript.media_path);
    assert!(media.is_file(), "{} is missing", media.display());
    assert_eq!(
        transcript.media_path,
        format!("media/{}.wav", transcript.id)
    );
    assert_eq!(
        std::fs::read(&media).expect("copy"),
        std::fs::read(&source).expect("source"),
        "the copy must be byte-for-byte the original"
    );

    // The peaks, computed during the decode.
    let peaks = world.library.load_peaks(&transcript.id).expect("peaks");
    assert_eq!(peaks.bucket_ms, DEFAULT_BUCKET_MS);
    assert_eq!(peaks.len(), 200, "4 s in 20 ms buckets");
    assert_eq!(
        peaks.downsample(96).len(),
        96,
        "the 96 bars of DESIGN.md §8"
    );

    // The record, the index and the queue.
    assert_eq!(
        world.library.load_transcript(&transcript.id).expect("json"),
        transcript
    );
    let row = world
        .library
        .db()
        .transcript_row(&transcript.id)
        .expect("row")
        .expect("indexed");
    assert_eq!(
        row.title, "Entretien Marchand",
        "title comes from the file name"
    );
    assert_eq!(row.sha256.len(), 64);
    assert_eq!(row.status, TranscriptStatus::Queued);

    let queue = world.library.db().queue().expect("queue");
    assert_eq!(queue.len(), 1);
    assert_eq!(queue[0].transcript_id, transcript.id);
}

#[test]
fn files_dropped_together_are_queued_in_the_order_they_were_dropped() {
    // CONCEPTION.md §6: « Dépôt multiple → mise en file dans l'ordre de dépôt ».
    let Some(world) = world() else { return };

    let mut expected = Vec::new();
    for (index, frequency) in [220, 440, 880].into_iter().enumerate() {
        // Distinct frequencies, or the three files would be byte-identical and the second would
        // legitimately come back as a duplicate.
        let source = world.produce(
            &format!("mémo {index}.wav"),
            &[
                "-f",
                "lavfi",
                "-i",
                &format!("sine=frequency={frequency}:sample_rate=44100:duration=1.5"),
            ],
        );
        expected.push(world.added(&source).id);
    }

    let queue: Vec<String> = world
        .library
        .db()
        .queue()
        .expect("queue")
        .into_iter()
        .map(|item| item.transcript_id)
        .collect();
    assert_eq!(queue, expected);
}

// ---------------------------------------------------------------------------------------------
// « Un .mp4 avec piste audio s'ingère ; un .mp4 muet est rejeté avec le message dédié »
// ---------------------------------------------------------------------------------------------

#[test]
fn an_mp4_with_sound_is_ingested_and_a_silent_one_is_refused_for_that_reason() {
    let Some(world) = world() else { return };

    let with_sound = world.produce(
        "réunion.mp4",
        &[
            "-f",
            "lavfi",
            "-i",
            "color=c=blue:s=64x64:r=10:d=3",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=44100:duration=3",
            "-shortest",
        ],
    );
    let transcript = world.added(&with_sound);
    assert!(
        transcript.duration_ms >= 2_900,
        "{}",
        transcript.duration_ms
    );

    let silent = world.produce(
        "muette.mp4",
        &["-f", "lavfi", "-i", "color=c=red:s=64x64:r=10:d=3"],
    );
    let error = world.refusal(&silent);

    assert_eq!(error.kind(), "aucune-piste-audio");
    assert!(error.to_string().contains("aucune piste audio"), "{error}");
    assert!(error.to_string().contains("vidéo muette"), "{error}");

    // A refusal must leave nothing behind: no orphan copy, no row, no queue entry.
    assert_eq!(world.library.db().count_transcripts().expect("count"), 1);
    assert_eq!(world.library.db().queue().expect("queue").len(), 1);
}

// ---------------------------------------------------------------------------------------------
// « Fichier corrompu, durée nulle, durée < 1 s : rejetés, messages distincts, en français »
// ---------------------------------------------------------------------------------------------

#[test]
fn corrupt_empty_and_too_short_files_are_refused_with_three_different_messages() {
    let Some(world) = world() else { return };

    // Corrupt: an mp3 extension over bytes that are not audio at all.
    let corrupt = world.sources.join("abîmé.mp3");
    std::fs::write(&corrupt, b"ceci n'est pas un fichier audio, pas du tout").expect("write");

    // Zero duration: a real, valid wav container holding no samples.
    let empty = world.produce(
        "vide.wav",
        &["-f", "lavfi", "-i", "anullsrc=sample_rate=44100", "-t", "0"],
    );

    // Under a second.
    let brief = world.tone("bref.wav", 0.4);

    let corrupt = world.refusal(&corrupt);
    let empty = world.refusal(&empty);
    let brief = world.refusal(&brief);

    assert_eq!(corrupt.kind(), "fichier-illisible");
    assert_eq!(empty.kind(), "media-vide");
    assert_eq!(brief.kind(), "trop-court");

    let messages = [corrupt.to_string(), empty.to_string(), brief.to_string()];
    for message in &messages {
        assert!(
            message.chars().any(|c| "éèêàçûôîù".contains(c)),
            "not a French sentence: {message}"
        );
    }
    assert_ne!(messages[0], messages[1]);
    assert_ne!(messages[1], messages[2]);
    assert_ne!(messages[0], messages[2]);

    assert!(messages[2].contains("400 ms"), "{}", messages[2]);
    assert_eq!(world.library.db().count_transcripts().expect("count"), 0);
}

#[test]
fn a_file_just_over_the_threshold_is_accepted() {
    // The boundary is worth pinning: an off-by-one here refuses perfectly good one-second memos.
    let Some(world) = world() else { return };

    let just_under = world.tone("juste-en-dessous.wav", 0.99);
    assert_eq!(world.refusal(&just_under).kind(), "trop-court");

    let just_over = world.tone("juste-au-dessus.wav", 1.01);
    let transcript = world.added(&just_over);
    assert!(transcript.duration_ms >= MINIMUM_DURATION_MS);
}

#[test]
fn a_truncated_mp4_is_refused_with_ffmpegs_reason_translated() {
    // CONCEPTION.md §8: « l'erreur ffmpeg traduite en langage clair ». A half-copied MP4 is the
    // case a user actually hits, and « moov atom not found » tells them nothing.
    let Some(world) = world() else { return };

    let complete = world.produce(
        "complète.mp4",
        &[
            "-f",
            "lavfi",
            "-i",
            "color=c=blue:s=64x64:r=10:d=3",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=44100:duration=3",
            "-shortest",
        ],
    );
    let bytes = std::fs::read(&complete).expect("read");
    let truncated = world.sources.join("interrompue.mp4");
    std::fs::write(&truncated, &bytes[..bytes.len() / 3]).expect("write");

    let error = world.refusal(&truncated);
    assert_eq!(error.kind(), "fichier-illisible");
    assert!(
        !error.to_string().contains("moov atom"),
        "the raw ffmpeg wording must not reach the user: {error}"
    );
}

#[test]
fn an_unsupported_extension_is_refused_without_launching_a_decoder() {
    let Some(world) = world() else { return };
    let path = world.sources.join("maquette.psd");
    std::fs::write(&path, b"pas du son").expect("write");

    let error = world.refusal(&path);
    assert_eq!(error.kind(), "format-non-pris-en-charge");
    assert!(error.to_string().contains("« .psd »"), "{error}");
}

#[test]
fn a_file_whose_name_starts_with_a_dash_is_ingested_like_any_other() {
    // ffmpeg's option parser has **no `--` separator**: handed `-mémo.wav`, ffprobe answers
    // « Unrecognized option 'mémo.wav' » and the file is refused as unreadable. The ingestion
    // makes the path absolute first, which is what makes this file ordinary.
    let Some(world) = world() else { return };
    let source = world.tone("-mémo bizarre.wav", 2.0);

    let transcript = world.added(&source);
    assert_eq!(transcript.title, "-mémo bizarre");
    assert!(transcript.duration_ms >= 1_900);
}

#[test]
fn the_record_keeps_an_absolute_source_path() {
    // What `absolute` guarantees, seen from the record: whatever the caller passed, the entry
    // names a path that can be reopened later. `Ingestor::absolute` is unit-tested on the
    // relative case; a temporary folder is on another volume than the crate, so a genuinely
    // relative path cannot be built here without moving the process's working directory.
    let Some(world) = world() else { return };
    let source = world.tone("chemin.wav", 2.0);
    let transcript = world.added(&source);

    assert!(
        Path::new(&transcript.source_path).is_absolute(),
        "{}",
        transcript.source_path
    );
}

#[test]
fn a_file_that_is_not_there_is_refused_as_missing() {
    let Some(world) = world() else { return };
    let error = world.refusal(&world.sources.join("jamais-existé.m4a"));
    assert_eq!(error.kind(), "fichier-introuvable");
}

// ---------------------------------------------------------------------------------------------
// « Un doublon est détecté par SHA-256 et propose les deux issues »
// ---------------------------------------------------------------------------------------------

#[test]
fn a_duplicate_is_detected_by_hash_and_both_outcomes_are_available() {
    let Some(world) = world() else { return };

    let first = world.tone("mémo.wav", 2.0);
    let original = world.added(&first);

    // The same bytes under another name and in another folder: only the hash can catch it.
    let elsewhere = world.sources.join("copie de mémo.wav");
    std::fs::copy(&first, &elsewhere).expect("copy");

    // Issue one — « ouvrir l'existante »: the ingestion stops and names what is already there.
    let outcome = world.ingest(&elsewhere).expect("ingest");
    match &outcome {
        Ingested::Duplicate { sha256, existing } => {
            assert_eq!(*sha256, original.sha256);
            assert_eq!(existing.len(), 1);
            assert_eq!(existing[0].id, original.id, "the entry to open");
        }
        Ingested::Added(_) => panic!("the duplicate was not detected"),
    }
    assert_eq!(
        world.library.db().count_transcripts().expect("count"),
        1,
        "asking must not have written anything"
    );

    // Issue two — « transcrire à nouveau »: a second, independent entry.
    let again = world
        .ingestor
        .ingest(&world.library, &elsewhere, DuplicatePolicy::TranscribeAgain)
        .expect("ingest");
    let Ingested::Added(second) = again else {
        panic!("TranscribeAgain must ingest")
    };

    assert_ne!(second.id, original.id);
    assert_eq!(second.sha256, original.sha256);
    assert_ne!(second.media_path, original.media_path, "its own copy");
    assert_eq!(world.library.db().count_transcripts().expect("count"), 2);
    assert!(world
        .library
        .paths()
        .resolve(&original.media_path)
        .is_file());
    assert!(world.library.paths().resolve(&second.media_path).is_file());
}

#[test]
fn two_different_files_of_the_same_length_are_not_duplicates() {
    // The hash has to be of the bytes, not of anything derived. Two tones of the same duration
    // and different frequency are the cheapest way to prove it is not the metadata being
    // compared.
    let Some(world) = world() else { return };

    let low = world.produce(
        "grave.wav",
        &[
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=220:sample_rate=44100:duration=2",
        ],
    );
    let high = world.produce(
        "aigu.wav",
        &[
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=880:sample_rate=44100:duration=2",
        ],
    );

    let first = world.added(&low);
    let second = world.added(&high);

    assert_ne!(first.sha256, second.sha256);
    assert_eq!(world.library.db().count_transcripts().expect("count"), 2);
}

// ---------------------------------------------------------------------------------------------
// « Les pics d'un fichier de 15 min pèsent moins de 200 Ko »
// ---------------------------------------------------------------------------------------------

#[test]
fn the_peaks_of_a_quarter_of_an_hour_stay_under_the_budget() {
    let Some(world) = world() else { return };

    // Fifteen minutes of varying tone, so the peaks are not a single repeated value.
    let source = world.produce(
        "quart-d-heure.wav",
        &[
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:beep_factor=4:sample_rate=16000:duration=900",
        ],
    );

    let transcript = world.added(&source);
    assert!(
        (899_000..=901_000).contains(&transcript.duration_ms),
        "duration {} ms",
        transcript.duration_ms
    );

    let file = world.library.paths().peaks(&transcript.id);
    let size = std::fs::metadata(&file).expect("peaks").len();
    assert!(size < 200 * 1024, "peaks weigh {size} bytes");

    // And they must still describe the recording: 15 min in 20 ms buckets.
    let peaks = world.library.load_peaks(&transcript.id).expect("peaks");
    assert_eq!(peaks.len(), 45_000);
    assert!(
        peaks.values.iter().any(|&value| value > 0),
        "a silent waveform would pass the size check and mean nothing"
    );
    eprintln!("pics de 15 min : {size} octets pour {} blocs", peaks.len());
}

// ---------------------------------------------------------------------------------------------
// « Un fichier de 2 h s'ingère sans dépasser 500 Mo de RSS »
// ---------------------------------------------------------------------------------------------

/// Peak working set of this process, in bytes.
///
/// Measured from inside the test rather than by watching it from a shell: the criterion is then
/// checked on every run instead of once, by hand, on the day the phase was written.
/// `K32GetProcessMemoryInfo` is exported by kernel32 itself, so nothing extra has to be linked.
#[cfg(windows)]
fn peak_working_set() -> u64 {
    /// `PROCESS_MEMORY_COUNTERS`. Only two fields are read; the rest are named with a leading
    /// underscore because they are there to give the struct the size the API checks against,
    /// not to be looked at.
    #[repr(C)]
    #[derive(Default)]
    struct Counters {
        cb: u32,
        _page_fault_count: u32,
        peak_working_set_size: usize,
        /// `WorkingSetSize`, then the six quota and pagefile counters.
        _rest: [usize; 7],
    }

    extern "system" {
        fn GetCurrentProcess() -> isize;
        fn K32GetProcessMemoryInfo(process: isize, counters: *mut Counters, size: u32) -> i32;
    }

    let mut counters = Counters {
        cb: std::mem::size_of::<Counters>() as u32,
        ..Default::default()
    };
    // SAFETY: `counters` is a live, correctly sized `PROCESS_MEMORY_COUNTERS`, and the handle
    // returned by `GetCurrentProcess` is a pseudo-handle that never needs closing.
    let ok = unsafe {
        K32GetProcessMemoryInfo(
            GetCurrentProcess(),
            &mut counters,
            std::mem::size_of::<Counters>() as u32,
        )
    };
    assert_ne!(ok, 0, "GetProcessMemoryInfo failed");
    counters.peak_working_set_size as u64
}

/// Long: it generates and then decodes two hours of audio. Run it explicitly.
///
/// ```text
/// cargo test --test ingest -- --ignored --nocapture two_hours
/// ```
#[test]
#[ignore = "generates and decodes two hours of audio — minutes, not seconds"]
#[cfg(windows)]
fn two_hours_of_audio_ingest_within_the_memory_budget() {
    const BUDGET: u64 = 500 * 1024 * 1024;
    const HOURS_MS: u64 = 2 * 3_600 * 1_000;

    let Some(world) = world() else { return };

    // 16 kHz mono at 32 kb/s: two hours in about 28 Mo on disk, and a decode that exercises the
    // streaming path for its full length. The beep factor keeps the waveform from being one
    // repeated value, so the peaks are real work rather than a run of identical bytes.
    let source = world.produce(
        "très-long.mp3",
        &[
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:beep_factor=4:sample_rate=16000:duration=7200",
            "-ac",
            "1",
            "-b:a",
            "32k",
        ],
    );

    let before = peak_working_set();
    let transcript = world.added(&source);
    let after = peak_working_set();

    eprintln!(
        "2 h ingérées — RSS crête {:.1} Mo (avant {:.1} Mo), source {:.1} Mo, durée {} ms",
        after as f64 / 1024.0 / 1024.0,
        before as f64 / 1024.0 / 1024.0,
        std::fs::metadata(&source).expect("metadata").len() as f64 / 1024.0 / 1024.0,
        transcript.duration_ms,
    );

    assert!(
        (HOURS_MS - 2_000..=HOURS_MS + 2_000).contains(&transcript.duration_ms),
        "duration {} ms is not two hours",
        transcript.duration_ms
    );
    assert!(
        after < BUDGET,
        "peak RSS {} bytes exceeds the 500 Mo budget",
        after
    );

    // The decoded PCM alone would be 460 Mo. Staying under the budget is only meaningful if the
    // peaks are complete, so check the waveform really covers the whole recording.
    let peaks = world.library.load_peaks(&transcript.id).expect("peaks");
    assert_eq!(peaks.len(), 360_000, "2 h in 20 ms buckets");
    assert!(peaks.values.iter().any(|&value| value > 0));
}

// ---------------------------------------------------------------------------------------------
// « Aucun appel à un ffmpeg du PATH »
// ---------------------------------------------------------------------------------------------

#[test]
fn ingestion_uses_the_bundled_binaries_and_nothing_else() {
    // The criterion is « vérifier en renommant le ffmpeg système ». Renaming a binary the whole
    // machine shares is not something a test may do, so the proof is taken from the other end:
    // the bundled pair is copied under names that exist on no PATH anywhere, and the ingestion
    // is run against those. If any call fell back to the PATH, this would still pass — so the
    // second half of the test removes the binaries entirely and checks that ingestion then
    // fails. A PATH fallback would make it succeed.
    let Some(world) = world() else { return };

    let private = world.sources.join("outils-privés");
    std::fs::create_dir_all(&private).expect("mkdir");
    let renamed = Tools::new(
        private.join("sillage-decodeur.exe"),
        private.join("sillage-sonde.exe"),
    );
    std::fs::copy(world.tools.path(Tool::Ffmpeg), renamed.path(Tool::Ffmpeg)).expect("copy");
    std::fs::copy(world.tools.path(Tool::Ffprobe), renamed.path(Tool::Ffprobe)).expect("copy");

    let source = world.tone("mémo.wav", 2.0);

    let ingestor = Ingestor::new(renamed.clone()).with_stabilization(Stabilization::immediate());
    let outcome = ingestor
        .ingest(&world.library, &source, DuplicatePolicy::Ask)
        .expect("the renamed binaries must work");
    assert!(matches!(outcome, Ingested::Added(_)));

    // Now with no binaries at all. ffmpeg is on this machine's PATH; if anything consulted it,
    // this ingestion would succeed instead of reporting an incomplete installation.
    let nowhere = Ingestor::new(Tools::in_directory(world.sources.join("vide")))
        .with_stabilization(Stabilization::immediate());
    let error = nowhere
        .ingest(&world.library, &source, DuplicatePolicy::Ask)
        .expect_err("no binaries, no ingestion");

    assert_eq!(error.kind(), "outil-manquant");
    assert!(error.to_string().contains("réinstallez"), "{error}");
}

// ---------------------------------------------------------------------------------------------
// « Attente de stabilisation »
// ---------------------------------------------------------------------------------------------

#[test]
fn a_file_still_being_written_is_waited_for_rather_than_ingested_truncated() {
    use std::io::Write;
    use std::time::Duration;

    let Some(world) = world() else { return };

    // A complete file, then the same bytes handed over in slices while the ingestion runs. The
    // ingestion must end up with the whole thing — a truncated wav decodes without error, just
    // shorter, which is precisely the failure that has to be prevented.
    let complete = world.tone("modèle.wav", 3.0);
    let bytes = std::fs::read(&complete).expect("read");

    let growing = world.sources.join("en-cours.wav");
    std::fs::write(&growing, &bytes[..bytes.len() / 8]).expect("write");

    let writing = {
        let (path, bytes) = (growing.clone(), bytes.clone());
        std::thread::spawn(move || {
            let mut written = bytes.len() / 8;
            while written < bytes.len() {
                let next = (written + bytes.len() / 8).min(bytes.len());
                let mut file = std::fs::OpenOptions::new()
                    .append(true)
                    .open(&path)
                    .expect("open");
                file.write_all(&bytes[written..next]).expect("append");
                drop(file);
                written = next;
                std::thread::sleep(Duration::from_millis(20));
            }
        })
    };

    let patient = Ingestor::new(world.tools.clone()).with_stabilization(Stabilization {
        poll: Duration::from_millis(60),
        settle: 2,
        timeout: Duration::from_secs(30),
    });
    let outcome = patient
        .ingest(&world.library, &growing, DuplicatePolicy::Ask)
        .expect("ingest");
    writing.join().expect("writer");

    let Ingested::Added(transcript) = outcome else {
        panic!("expected an entry")
    };
    assert!(
        transcript.duration_ms >= 2_900,
        "ingested only {} ms of a 3 s file — the wait did not hold",
        transcript.duration_ms
    );
    assert_eq!(
        std::fs::read(world.library.paths().resolve(&transcript.media_path)).expect("copy"),
        bytes,
        "the copy must be the finished file"
    );
}
